**NUMPY**

**problem-1**

In [2]:
import numpy as np
list_ = ['1','2','3','4','5' ]
array_list = np.array(object = list_)

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.**

**yes because list_ is of list type and array_list of type array that we convert from a list with the help of numpy**

In [3]:
print(type(list_ ))
print(type(array_list ))

<class 'list'>
<class 'numpy.ndarray'>


**problem-2**

**Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.**

In [4]:
list_ = ['1','2','3','4','5' ]
for i in list_:
  print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
array_list = np.array(object = list_)
for i in array_list:
  print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


**Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.**

In [7]:
list_ = ['1','2','3','4','5' ]
array_list = np.array(object = list_, dtype = int)
for i in list_:
  print(type(i))

for j in array_list:
  print(type(j))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


**Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size**

In [8]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [10]:
#(i) shape

num_array.shape

(2, 3)

In [11]:
#(ii) size
num_array.size

6

**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]**

In [12]:
import numpy as np

b = np.zeros((3,3), dtype = int)
print("Matrix b : \n", b)

Matrix b : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


**Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]**

In [14]:
import numpy as np
a=np.identity(5, dtype=None, like=None)
print("Matrix a : \n", a)

Matrix a : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
